#!usr/bin/env python

import argparse
import datetime
import pprint

import fmiapi

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("api_key", help="FMI API key.")
    parser.add_argument("fmisid", help="FMISID of the station.")
    parser.add_argument("-t", "--timesteps", default=1, help="Timesteps.")
    args = parser.parse_args()

    endtime = datetime.datetime.utcnow().replace(microsecond=0)
    starttime = endtime - datetime.timedelta(minutes=20) 

    params = {
            'request' : 'getFeature',
            'storedquery_id' : 'fmi::observations::weather::simple',
            'fmisid' : args.fmisid,
            'timesteps' : args.timesteps,
            'endtime' : endtime.isoformat() + 'Z',
            'starttime' : starttime.isoformat() + 'Z'
    }

    results = fmiapi.fmi_observations_weather_simple(args.api_key, params)
    if results:
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint(results)

if __name__ == "__main__":
    main()
